# Generated by Django 5.1.3 on 2024-12-09 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcomment',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurantDashboard.food'),
        ),
        migrations.AlterField(
            model_name='restaurantcomment',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurantDashboard.restaurant'),
        ),
    ]
