# Generated by Django 5.1.3 on 2024-12-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
