# Generated by Django 5.1.3 on 2024-12-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_dislikes_count_comment_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes_count',
        ),
    ]
