# Generated by Django 5.1.3 on 2024-12-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_remove_comment_dislikes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes_count',
            new_name='like_count',
        ),
    ]
