# Generated by Django 5.1.3 on 2024-12-23 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0004_address_street'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'shipping_address', 'status')},
        ),
    ]
