# Generated by Django 5.1.3 on 2024-12-15 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='foods/default.jpg', upload_to='foods')),
                ('count', models.PositiveIntegerField()),
                ('rate', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'natural'), ('4', 'good'), ('5', 'very good')], default='5', max_length=1)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveBigIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
